### ISSUE TITLE
Experimental --de argument not working - form button ids wrong

### ISSUE THREAD

**Issue by Z0n1** [pspeter/statement-dl#6]
running with the --de argument stops the script, returns:
"selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //input[@id="loginForm_userId"]"

The form input ids for UserId, password and login button on the DE login page are different, so the --de argument would need to swich these IDs as well.
For DE it must be "loginForm_txtUserId" and "loginForm_txtPassword_txtPassword" and "loginForm_loginButton"

After changing these IDs in lines 128, 129, 144 and 146 accordingly, the script worked perfectly for my DE account.

Attached my working flatex.py file.
**EDIT:** Just built in the switch myself, and it works. Changed the _login() function to take the de argument and the download_documents() function passes it upon calling it. inside _login() the form ids are used based on the de argument.
Feel free to review:
[flatex.txt](https://github.com/pspeter/statement-dl/files/10472384/flatex.txt)

Thanks a lot for this tool and your work! Exactly what i was looking for.

P.S. (Tool just finished downloading all files!)

**Comment by pspeter** [comment]
Hey there! I don't have a flatex.de account so I'm relying on other users to test that, so thanks for your input! Happy it works for you now.
I will put in your changes and draft up a new release. Thanks again!

**Comment by Z0n1** [comment]
Hi, 
just updated the package to your newest release and tested, all working now!
No problem to help with further DE-specific testing, just let me know!
Thanks

**Comment by pspeter** [comment]
Cool, thanks for your feedback.
Just open another issue if something breaks. Also happy to review and merge any PR if you want to add or fix something yourself.
